src/Ofgem.GBI.ExternalPortal.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ofgem.GBI.ExternalPortal.Application.UserManagement.Constants;

namespace Ofgem.GBI.ExternalPortal.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true), AllowAnonymous]
    public class ErrorModel : PageModel
    {
        private readonly string _linkedAccountError = DecorateString("You cannot access the Great British Insulation Scheme (GBIS) as you're not signed into an account with Ofgem.", "error-paragraph-no-access") +
                                    DecorateString("You are currently only signed in with your One Login account.", "error-paragraph-no-linked-acct") +
                                    DecorateString("Accessing and using the Great British Insulation Scheme", "error-header-using-gbis", "h2", "govuk-heading-m") +
                                    DecorateString("To get access to and use the Great British Insulation Scheme, you need to request an account from Ofgem.", "error-paragraph-acct-request") +
                                    DecorateString("To request an account, you should send an email to Ofgem at ((email address here)).", "error-paragraph-email") +
                                    DecorateString("You should send this email to Ofgem from the same email address you used to create your GOV UK One Login account. This is the only way we can match your Great British Insulation Scheme account to your GOV UK One Login account.", "error-paragraph-link-acct") +
                                    DecorateString("After you've sent this email with the request, the Ofgem team will be in touch about creating an account for you.", "error-paragraph-acct-creation");

        private bool _hasLinkedAccount = false;

        public string? ExceptionMessage { get; set; } = string.Empty;

        public void OnGet(int? statusCode = null)
        {
            if (statusCode == null)
            {
                return;
            }

            _hasLinkedAccount = User.Claims.Any(c => c.Type == ClaimsConstants.LinkedAccount);

            ExceptionMessage = SetExceptionMessage(statusCode.Value);
        }

        private string SetExceptionMessage(int statusCode) => statusCode switch
        {
            400 => DecorateString("We are unable to process your request at this time, please try again later.", "error-paragraph-error-message"),
            401 => DecorateString("You do not have an permission to use the Great British Insulation Scheme service.", "error-paragraph-error-message"),
            403 when !_hasLinkedAccount => _linkedAccountError,
            403 => DecorateString("You do not have an permission to use the Great British Insulation Scheme service.", "error-paragraph-error-message"),
            404 when !_hasLinkedAccount => _linkedAccountError,
            404 => DecorateString("This page cannot be found.", "error-paragraph-error-message"),
            _ => DecorateString("We are unable to process your request at this time, please try again later.", "error-paragraph-error-message")
        };

        private static string DecorateString(string value, string dataTestId, string elementType = "p", string cssClass = "govuk-body")
        {
            return $"<{elementType} class=\"{cssClass}\" date-test-id=\"{dataTestId}\">{value}</{elementType}>";
        }

    }
}

src/Ofgem.GBI.ExternalPortal.Web/Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ofgem.GBI.ExternalPortal.Application.MeasureValidation.Models;
using Ofgem.GBI.ExternalPortal.Application.MeasureValidation.Services;
using Ofgem.GBI.ExternalPortal.Application.UserManagement.Constants;
using Ofgem.GBI.ExternalPortal.Web.Models;
using System.Text;

namespace Ofgem.GBI.ExternalPortal.Web.Pages
{
    [Authorize(Policy = nameof(PolicyNames.IsAuthenticated))]
    [Authorize(Policy = ClaimsConstants.LinkedAccount)]
    public class HomeModel : PageModel
    {
        private readonly IMeasureValidationService measureValidationService;
        private readonly IHttpContextAccessor httpContextAccessor;

        public IEnumerable<FileWithErrorsMetadata> LatestValidationResults { get; set; } = Array.Empty<FileWithErrorsMetadata>();

        public HomeModel(IMeasureValidationService measureValidationService, IHttpContextAccessor httpContextAccessor)
        {
            this.measureValidationService = measureValidationService;
            this.httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> OnGet()
        {
            var user = httpContextAccessor.HttpContext!.User;
            string? supplierName = user.Claims.SingleOrDefault(x => x.Type == "SupplierName")?.Value;
            if (supplierName != null)
            {
                FilesWithErrorsMetadata filesWithErrorsMetadata = await measureValidationService.GetLatestFilesWithErrorsMetadata(supplierName);
                LatestValidationResults = filesWithErrorsMetadata.FilesWithErrors;
            }

            return Page();
        }

        public async Task<IActionResult> OnGetDownloadErrorReport(string documentId, string stage, string fileName)
        {
            var ext = Path.GetExtension(fileName);
            var name = Path.GetFileNameWithoutExtension(fileName);

            var fileContent = Encoding.UTF8.GetBytes(await measureValidationService.GetStageErrorReport(documentId, stage));
            return File(fileContent, "application/text", $"{name}_Errors{ext}");
        }
    }
}

src/Ofgem.GBI.ExternalPortal.Web/Pages/IsActive.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ofgem.GBI.ExternalPortal.Web.Models;

namespace Ofgem.GBI.ExternalPortal.Web.Pages
{
    [Authorize(Policy = nameof(PolicyNames.IsActiveAccount))]
    public class IsActiveModel : PageModel
    {
    }
}

src/Ofgem.GBI.ExternalPortal.Web/Pages/SignOut.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ofgem.GBI.ExternalPortal.Web.Pages
{
    [AllowAnonymous]
    public class SignOutModel : PageModel
    {
    }
}

src/Ofgem.GBI.ExternalPortal.Web/Pages/Home.cshtml
@page

@model Ofgem.GBI.ExternalPortal.Web.Pages.HomeModel
@{
}

<style>
    .govuk-notification-banner--error {
        border-color: #942514;
        background-color: #942514;
    }

    .govuk-notification-banner__header {
        padding: 2px 15px 5px;
        border-bottom: 1px solid transparent;
    }

    .govuk-notification-banner__title {
        font-family: "GDS Transport", arial, sans-serif;
        -webkit-font-smoothing: antialiased;
        font-weight: 700;
        font-size: 1rem;
        line-height: 1.25;
        margin: 0;
        padding: 0;
        color: #ffffff;
    }

    .govuk-\!-margin-bottom-5 {
        margin-bottom: 15px !important;
    }

    .card {
        height: 180px;
        color: white;
        border: 1px solid #b1b4b6;
        border-bottom-width: 4px;
    }

    .govuk-sectio-break--l {
        margin: 30px 0;
    }

    .header-break {
        margin-top: 40px;
    }

    .footer-break{
        margin-bottom: 40px;
    }

</style>
<div class="govuk-width-container">
    
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-full">

                <h1 class="govuk-heading-xl header-break" data-test-id="page-heading"> Great British Insulation Scheme </h1>
                <a class="govuk-button" data-test-id="btn-upload-measure-button" asp-page="Measures/UploadMeasures"> Upload a measure file </a>
                <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

                @if (@Model.LatestValidationResults.Any())
                {
                    <div class="govuk-notification-banner govuk-notification-banner--error" data-test-id="notification-banner" role="alert"
                     aria-labelledby="govuk-notification-banner-title"
                     data-module="govuk-notification-banner">
                        <div class="govuk-notification-banner__header" data-test-id="notification-banner-header">
                            <h2 class="govuk-notification-banner__title" data-test-id="notification-banner-title" id="govuk-notification-banner-title">
                                Latest error reports
                            </h2>
                        </div>

                        <div class="govuk-notification-banner__content" data-test-id="notification-banner-content">
                            <h3 class="govuk-notification-banner__heading" data-test-id="banner-heading-message">The following files you uploaded include measures containing errors</h3>

                            <table class="govuk-table" data-test-id="dtable">
                                <thead class="govuk-table__head" data-test-id="table-header">
                                    <tr class="govuk-table__row" data-test-id="table-row">
                                        <th scope="col" class="govuk-table__header app-custom-class" data-test-id="column-header">Date</th>
                                        <th scope="col" class="govuk-table__header app-custom-class" data-test-id="column-header">Time</th>
                                        <th scope="col" class="govuk-table__header app-custom-class" data-test-id="column-header">File name</th>
                                        <th scope="col" class="govuk-table__header app-custom-class" data-test-id="column-header">Error Stage</th>
                                        <th scope="col" class="govuk-table__header app-custom-class" data-test-id="column-header">Action</th>
                                    </tr>
                                </thead>
                                <tbody class="govuk-table__body" data-test-id="latest-validation-results">
                                    @{
                                        foreach (var latestValidationResult in @Model.LatestValidationResults)
                                        {
                                            <tr class="govuk-table__row" data-test-id="validation-results-row">
                                                <th scope="row" class="govuk-table__header" data-test-id="validation-result-date">@latestValidationResult.DateTime.ToShortDateString()</th>
                                                <th scope="row" class="govuk-table__header" data-test-id="validation-result-time">@latestValidationResult.DateTime.ToString(@"h\:mm tt")</th>
                                                <td class="govuk-table__cell" data-test-id="validation-result-file-name">@latestValidationResult.FileName</td>
                                                <td class="govuk-table__cell" data-test-id="validation-result-error-stage">@latestValidationResult.ErrorStage</td>
                                                <td class="govuk-table__cell"><a asp-page-handler="DownloadErrorReport" asp-route-documentId=@latestValidationResult.DocumentId asp-route-fileName=@latestValidationResult.FileName asp-route-stage=@latestValidationResult.ErrorStage data-test-id="latest-error-report">Download error report</a></td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                            <p class="govuk-body"><a class="govuk-link" asp-page="/ErrorReports/ExistingErrorReports" data-test-id="home-existing-error-link">View all error reports</a></p>
                        </div>
                    </div>
                    <hr class="govuk-section-break govuk-sectio-break--l govuk-section-break--visible" />
                }
            </div>
        </div>
 
        <div class="govuk-grid-row footer-break">
            <div class="govuk-grid-column-one-third govuk-!-margin-bottom-5">
                <div class="card govuk-!-padding-5">
                    <h3 class="govuk-heading-m"><a data-test-id="home-manage-measures-card-link" asp-page="/Measures/ManageMeasures" class="govuk-link">Managing measures</a></h3>
                    <p class="govuk-body">Upload new measure files, view status on previously uploaded files and view file extensions.</p>
                </div>
            </div>

           <div class="govuk-grid-column-one-third govuk-!-margin-bottom-5">
                <div class="card govuk-!-padding-5">
                    <h3 class="govuk-heading-m"><a data-test-id="home-existing-error-reports-card-link" asp-page="/ErrorReports/ExistingErrorReports" class="govuk-link">View all error reports</a></h3>
                    <p class="govuk-body">View and download all existing error reports.</p>
                </div>
            </div>
        </div>
    
</div>
<hr class="govuk-section-break govuk-sectio-break--l govuk-section-break--visible" />

<h3 class="govuk-heading-l">Get help</h3>
<p><a href="#" target="_blank">How to upload a measure (opens in a new tab)</a></p>
<p><a href="#" target="_blank">What you will need to upload a Measure (opens in a new tab)</a></p>

src/Ofgem.GBI.ExternalPortal.Web/Pages/IsActive.cshtml
@page
@model IsActiveModel
@using System.Security.Claims
@using Ofgem.GBI.ExternalPortal.Application.UserManagement.Constants

<h1 class="govuk-heading-xl">POC Auth - Active check</h1>

<p>Name: @HttpContext.User.Identity?.Name</p>
<p>Email: @HttpContext.User.Claims.FirstOrDefault(c=>c.Type.Equals(ClaimTypes.Email))?.Value</p>
<p>Sub: @HttpContext.User.Claims.FirstOrDefault(c=>c.Type.Equals(ClaimTypes.NameIdentifier))?.Value</p>
<p>CustomClaim AccountId: @HttpContext.User.Claims.FirstOrDefault(c=>c.Type.Equals("EmployerAccountId"))?.Value</p>
<a asp-route="/@OneLoginConstants.SignOutUrl" class="govuk-button">Sign Out</a>

src/Ofgem.GBI.ExternalPortal.Web/Pages/SignOut.cshtml
@page
@model Ofgem.GBI.ExternalPortal.Web.Pages.SignOutModel
@{
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds ">
        <input type="hidden" name="_csrf" value="OrvybYly-mXzFfompX9Z-uYajBSEdXGkHeFc">
        <h1 data-test-id="sign-out-header" class="govuk-heading-l govuk-!-margin-top-0 govuk-!-margin-bottom-3">You have signed out</h1>
        <p class="govuk-body" data-test-id="sign-out-paragraph-confirmation">
            You are now signed out of the Great British Insulation Scheme.
        </p>
        <p class="govuk-body" data-test-id="sign-out-paragraph-sign-back-in">
            You can return to <a href="https://www.gov.uk/" class="govuk-link">GOV.UK homepage</a> or sign back into the portal.
        </p>
        <p>
            <a data-test-id="sign-out-link-sign-in" href="/home" class="govuk-button">Sign in</a>
        </p>
    </div>
</div>