src/Ofgem.GBI.ExternalPortal.Web/Pages/Measures/ManageMeasures.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ofgem.GBI.ExternalPortal.Application.UserManagement.Constants;
using Ofgem.GBI.ExternalPortal.Web.Models;

namespace Ofgem.GBI.ExternalPortal.Web.Pages.Measures
{
    [Authorize(Policy = nameof(PolicyNames.IsAuthenticated))]
    [Authorize(Policy = ClaimsConstants.LinkedAccount)]
    public class ManageMeasuresModel : PageModel
    {
        private readonly ILogger<ManageMeasuresModel> logger;

        public ManageMeasuresModel(ILogger<ManageMeasuresModel> logger)
        {
            this.logger = logger;
        }

        public void OnGet()
        {
            logger.LogInformation("User Authenticated");
        }
    }
}

src/Ofgem.GBI.ExternalPortal.Web/Pages/Measures/MeasureFileUploaded.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ofgem.GBI.ExternalPortal.Application.MeasureValidation.Services;
using Ofgem.GBI.ExternalPortal.Application.UserManagement.Constants;
using Ofgem.GBI.ExternalPortal.Web.Models;
using System.Text;

namespace Ofgem.GBI.ExternalPortal.Web.Pages.Measures
{
    [Authorize(Policy = nameof(PolicyNames.IsAuthenticated))]
    [Authorize(Policy = ClaimsConstants.LinkedAccount)]
    public class MeasureFileUploadedModel : PageModel
    {
        private readonly IMeasureValidationService _measureValidationService;

        public int NumberOfMeasureValidationErrors { get; set; }

        public int NumberOfMeasureValidationSuccesses { get; set; }

        public string? DocumentId { get; set; }
        public string? FileName { get; set; }

        public MeasureFileUploadedModel(IMeasureValidationService measureValidationService)
        {
            this._measureValidationService = measureValidationService;
        }

        public async Task<IActionResult> OnGet(string documentId)
        {
            var coreValidationResult = await _measureValidationService.GetCoreValidationResult(documentId);
            NumberOfMeasureValidationErrors = coreValidationResult.FailedCount;
            NumberOfMeasureValidationSuccesses = coreValidationResult.SuccessCount;
            DocumentId = documentId;
            FileName = coreValidationResult.FileName;

            return Page();
        }

        public async Task<IActionResult> OnGetDownloadStage1Report(string documentId, string fileName)
        {
            var ext = Path.GetExtension(fileName);
            var name = Path.GetFileNameWithoutExtension(fileName);

            var fileContent = Encoding.UTF8.GetBytes(await _measureValidationService.GetStage1ErrorReport(documentId));
            return File(fileContent, "application/text", $"{name}_Errors{ext}");
        }
    }
}

src/Ofgem.GBI.ExternalPortal.Web/Pages/Measures/UploadMeasures.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ofgem.GBI.ExternalPortal.Application.UploadMeasure;
using Ofgem.GBI.ExternalPortal.Application.UploadMeasure.Models;
using Ofgem.GBI.ExternalPortal.Application.UserManagement.Constants;
using Ofgem.GBI.ExternalPortal.Web.Common.Helpers;
using Ofgem.GBI.ExternalPortal.Web.Measures.UploadMeasures.MeasuresCSVValidator;
using Ofgem.GBI.ExternalPortal.Web.Models;
using System.Security.Claims;

namespace Ofgem.GBI.ExternalPortal.Web.Pages.Measures;
[Authorize(Policy = nameof(PolicyNames.IsAuthenticated))]
[Authorize(Policy = ClaimsConstants.LinkedAccount)]
public class UploadMeasuresModel : PageModel
{

    public bool FailedCsvValidation { get; set; }
    public MeasuresCsvErrors? MeasuresCsvErrors { get; set; }

    private readonly IMeasuresCsvValidator _measuresCsvValidator;
    private readonly ILogger<UploadMeasuresModel> _logger;
    private readonly IUploadMeasureService _uploadMeasureService;

    [BindProperty]
    public IFormFile? MeasuresUploadFile { get; set; }

    public UploadMeasuresModel(IMeasuresCsvValidator measuresCsvValidator, ILogger<UploadMeasuresModel> logger, IUploadMeasureService uploadMeasureService)
    {
        _logger = logger;
        _measuresCsvValidator = measuresCsvValidator;
        _uploadMeasureService = uploadMeasureService;
    }

    public async Task<IActionResult> OnPost(IFormFile measuresUploadFile)
    {
        _logger.LogInformation("Measures file submitted");

        try
        {
            MeasuresCsvErrors = _measuresCsvValidator.ValidateCsv(measuresUploadFile);

            FailedCsvValidation = MeasuresCsvErrors.hasErrors();

            if (FailedCsvValidation)
            {
                _logger.LogInformation("Uploaded measures file has errors");
            }
            else
            {
                var supplierName = ClaimsHelper.GetClaimValue(ClaimsConstants.SupplierName, User.Identity as ClaimsIdentity);
                MeasuresCsvUploadResponse response = await _uploadMeasureService.UploadMeasureToDocumentsService(measuresUploadFile, supplierName);

                string? documentId = response.DocumentId;
                string url = "MeasureFileUploaded";
                return RedirectToPage(url, new { documentId });
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"{ex.Message}", ex.Message);
        }

        return Page();
    }
}

src/Ofgem.GBI.ExternalPortal.Web/Pages/Measures/ManageMeasures.cshtml
@page
@using Ofgem.GBI.ExternalPortal.Application.UserManagement.Constants;
@model Ofgem.GBI.ExternalPortal.Web.Pages.Measures.ManageMeasuresModel
@{
}
<a data-test-id="manage-measures-a-back-button" type="submit" class="govuk-back-link" asp-page="/Home">Back</a>

<h1 class="govuk-heading-l"> Manage measures </h1>

<a data-test-id="manage-measures-navigate-form" asp-page="./UploadMeasures" class="govuk-button">
    Upload a measure file
</a>
<br />
<a data-test-id="manage-measures-a-sign-out" href="/@OneLoginConstants.SignOutUrl" class="govuk-button">Sign Out</a>

src/Ofgem.GBI.ExternalPortal.Web/Pages/Measures/MeasureFileUploaded.cshtml
@page
@model MeasureFileUploadedModel
@{
    var anyValidationErrors = Model.NumberOfMeasureValidationErrors > 0;
    var uploadMeasuresPageName = "UploadMeasures";
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation" data-test-id="pnl-confirmation">
            <h1 class="govuk-panel__title" data-test-id="pnlTitle">
                File uploaded
            </h1>
        </div>

        @if (anyValidationErrors) {
            <h2 class="govuk-heading-l" data-test-id="txt-heading-error">This file has errors</h2>

            <p class="govuk-body" data-test-id="error-body">The file contains @Model.NumberOfMeasureValidationErrors measures with errors. These measures with errors have:</p>

            <ul class="govuk-list govuk-list--bullet" data-test-id="lst-errors">
                <li data-test-id="lst-errors-item-1">failed the core stage checks</li>
                <li data-test-id="lst-errors-item-2">not been uploaded into the Great British Insulation Scheme register</li>
            </ul>

            <p class="govuk-body" data-test-id="txt-download-error-report">You need to download the error report containing the unsuccessful measures to find out why they have failed. You will also receive these errors via email.</p>
        } else {
            <p class="govuk-body" data-test-id="txt-no-errors">The core checks found no errors with this file.</p>
            <p class="govuk-body" data-test-id="txt-measures-added">The measures have been added to the Great British Insulation Scheme (GBIS) register.</p>
        }
        <h2 class="govuk-heading-l" data-test-id="txt-heading-what-happens-next">What happens next?</h2>

        @if (anyValidationErrors) {
            <p class="govuk-body" data-test-id="txt-success-measures-additional-checks">The remaining @Model.NumberOfMeasureValidationSuccesses measures without errors will now go through additional checks to validate the information in the file.</p>
            <p class="govuk-body" data-test-id="txt-error-measures-no-additional-checks">The measures in the file that contain errors will not progress for additional checks. You must fix these before progressing.</p>

            <h3 class="govuk-heading-m" data-test-id="txt-heading-fixing-errors">Fixing the errors in the file</h3>

            <p class="govuk-body" data-test-id="txt-must-fix-errors">Before you can progress, you must fix the measures containing errors.</p>
            <p class="govuk-body" data-test-id="txt-fix-errors-to-do">To do this, you must:</p>
            <ol class="govuk-list govuk-list--number" data-test-id="lst-fix-errors">
                <li data-test-id="lst-fix-errors-item-1">Download the error report.</li>
                <li data-test-id="lst-fix-errors-item-2">Follow the instructions in the error report to fix the measures with errors.</li>
                <li data-test-id="lst-fix-errors-item-3">Reupload the measures that failed the core stage checks in this Great British Insulation Scheme portal.</li>
            </ol>

            <h2 class="govuk-heading-l" data-test-id="txt-heading-download-error-report">Downloading your error report</h2>

            <div class="govuk-warning-text">
                <span class="govuk-warning-text__icon" aria-hidden="true" data-test-id="icn-warning">!</span>
                <strong class="govuk-warning-text__text" data-test-id="txt-warning">
                    <span class="govuk-warning-text__assistive">Warning</span>
                    Warning. This is the only opportunity to download the report containing the core check errors.
                </strong>
            </div>

            <p class="govuk-body" data-test-id="txt-single-download">If you do not download it here, you'll be unable to access it afterwards and have to upload your file again to generate the error report.</p>

            <div class="govuk-button-group" data-test-id="btn-download-error-report">
                <a class="govuk-button" data-module="govuk-button" asp-page-handler="DownloadStage1Report" asp-route-documentId=@Model.DocumentId asp-route-fileName=@Model.FileName>
                    Download error report
                </a>
            </div>

            <h3 class="govuk-heading-m" data-test-id="txt-heading-upload">Upload another measure file</h3>

            <p class="govuk-body">
                <a href="@uploadMeasuresPageName" data-test-id="lnk-upload-measure-file">Upload another measure file</a>
            </p>
        } else {
            <p class="govuk-body" data-test-id="txt-no-errors-additional-checks">The file will now go through several additional checks. We'll take a closer look at the file to check if there are any errors with the details in the file.</p>

            <h3 class="govuk-heading-m" data-test-id="txt-heading-additional-checks-no-errors">If no errors are found during additional checks</h3>
            <p class="govuk-body" data-test-id="txt-additional-checks-no-errors">If the measures in the file pass the additional checks and no errors are found, these measures will be updated on the Great British Insulation Scheme register.</p>

            <h3 class="govuk-heading-m" data-test-id="txt-heading-additional-checks-errors">If errors are found during additional checks</h3>
            <p class="govuk-body" data-test-id="txt-additional-checks-errors-1">If the measures are found to have errors during the additional checks, these will not be updated on the register.</p>
            <p class="govuk-body" data-test-id="txt-additional-checks-errors-2">We'll let you know about this by email. We'll send this to the email address you used to create an account with us.</p>
            <p class="govuk-body" data-test-id="txt-additional-checks-errors-3">You'll be able to access any error reports relating to the file on the homepage.</p>


            <h2 class="govuk-heading-l" data-test-id="txt-heading-additional-file-upload">Have more than one file to upload?</h2>
            <p class="govuk-body" data-test-id="txt-additional-file-upload">You can upload any additional measure files you have here.</p>
            <form method="get" asp-page="@uploadMeasuresPageName">
                <button type="submit" class="govuk-button" data-module="govuk-button" data-test-id="btn-upload-measure-button">Upload another measure</button>
            </form>
        }
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
        <p class="govuk-body">
            <a href="/Home" data-test-id="lnk-homepage">Return to homepage</a>
        </p>
    </div>
</div>

src/Ofgem.GBI.ExternalPortal.Web/Pages/Measures/UploadMeasures.cshtml
@page
@model Ofgem.GBI.ExternalPortal.Web.Pages.Measures.UploadMeasuresModel
@using Ofgem.GBI.ExternalPortal.Web.Common.Constants
@functions {
}

@if (Model.FailedCsvValidation)
{
	ViewData["Title"] = "Error: Measures Upload Page";
}
else {
	ViewData["Title"] = "Measures Upload Page";
}

<style>
	.custom-file-upload {
		font-size: 1.1875rem;
		line-height: 1.3157894737;
		color: #0b0c0c;
		font-family: "GDS Transport", arial, sans-serif;
		-webkit-font-smoothing: antialiased;
		border: 1px solid #ccc;
		display: inline-block;
		padding: 6px 12px;
		cursor: pointer;
		margin: 0;
	}
    .upload-img {
        position: relative;
        top: 5px;
	}
	.custom-file-input {
		font-family: "GDS Transport", arial, sans-serif;
		color: #0b0c0c;
		font-size: 1.1875rem;
		height: 24px;
		-webkit-font-smoothing: antialiased;
		line-height: 1.3157894737
	}

	input[type=file]::file-selector-button {
		display: none;
	}
</style>

<a data-test-id="upload-measures-a-back-button" type="submit" class="govuk-back-link" asp-page="/Home">Back</a>

<div id="measures-upload-component">

    @if (Model.FailedCsvValidation)
    {
        <div data-test-id="upload-measures-div-error-list" class="govuk-error-summary" data-module="govuk-error-summary">
            <div role="alert">
                <h2 class="govuk-error-summary__title"> There is a problem </h2>
                <div class="govuk-error-summary__body">
                    <ul class="govuk-list govuk-error-summary__list">

						@{
							if (Model?.MeasuresCsvErrors?.NoFileSelected == true)
							{
								<li data-test-id="upload-measures-li-no-file-error-message"> <a href="#meaures-upload-form">@(UploadMeasuresConstants.TemplateText.CsvValidationNoFileText)</a> </li>
							}
							if (Model?.MeasuresCsvErrors?.FileIsEmpty == true)
							{
								<li data-test-id="upload-measures-li-empty-file-error-message"> <a href="#meaures-upload-form">@(UploadMeasuresConstants.TemplateText.CsvValidationFileIsEmptyText)</a> </li>
							}
							if (Model?.MeasuresCsvErrors?.InvalidFileType == true)
							{
								<li data-test-id="upload-measures-li-invalid-filetype-error-message"> <a href="#meaures-upload-form">@(UploadMeasuresConstants.TemplateText.CsvValidationInvalidFileTypeText)</a> </li>
							}
							if (Model?.MeasuresCsvErrors?.NotGbisSchema == true)
							{
								<li data-test-id="upload-measures-li-invalid-header-error-message"> <a href="#meaures-upload-form">@(UploadMeasuresConstants.TemplateText.CsvValidationNotGBISSchemaText)</a> </li>
							}
							if (Model?.MeasuresCsvErrors?.ExceedsMaxRows == true)
							{
								<li data-test-id="upload-measures-li-maxrows-error-message"> <a href="#meaures-upload-form">@(UploadMeasuresConstants.TemplateText.CsvValidationExceedsMaxRowsText)</a> </li>
							}
							if (Model?.MeasuresCsvErrors?.ExceedsMaxFileSize == true)
							{
								<li data-test-id="upload-measures-li-maxfilesize-error-message"> <a href="#meaures-upload-form">@(UploadMeasuresConstants.TemplateText.CsvValidationExceedsMaxFileSizeText)</a> </li>
							}
						}

					</ul>
				</div>
			</div>
		</div>

    }


    <h1 class="govuk-heading-xl"> Upload measures file </h1>

    <p class="govuk-body"> Any file containing measures you upload must be a CSV file.</p>

    <br>

	<div data-test-id="upload-measures-class-govuk-error-style" class="govuk-form-group @(Model?.FailedCsvValidation == true ? "govuk-form-group--error" : "" ) ">

		<form  data-test-id="upload-measures-form-upload-measures-csv" method="post" enctype="multipart/form-data" id="measures-upload-form" novalidate>

			<label for="file-upload" class="custom-file-upload">
				<svg class="upload-img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
					<path d="M11 14.9861C11 15.5384 11.4477 15.9861 12 15.9861C12.5523 15.9861 13 15.5384 13 14.9861V7.82831L16.2428 11.0711L17.657 9.65685L12.0001 4L6.34326 9.65685L7.75748 11.0711L11 7.82854V14.9861Z" fill="currentColor" />
					<path d="M4 14H6V18H18V14H20V18C20 19.1046 19.1046 20 18 20H6C4.89543 20 4 19.1046 4 18V14Z" fill="currentColor" />
				</svg> Choose file
			</label>

		@if (Model?.FailedCsvValidation == true)
		{
			<div data-test-id="upload-measures-div-form-error-list" class="govuk-error-summary__body">
				@{
					if (Model?.MeasuresCsvErrors?.NoFileSelected == true)
					{
						<p data-test-id="upload-measures-p-no-file-error-message" class="govuk-error-message">@(UploadMeasuresConstants.TemplateText.CsvValidationNoFileText)</p>
					}
					if (Model?.MeasuresCsvErrors?.FileIsEmpty == true)
					{
						<p data-test-id="upload-measures-p-empty-file-error-message" class="govuk-error-message">@(UploadMeasuresConstants.TemplateText.CsvValidationFileIsEmptyText)</p>
					}
					if (Model?.MeasuresCsvErrors?.InvalidFileType == true)
					{
						<p data-test-id="upload-measures-p-invalid-filetype-error-message" class="govuk-error-message">@(UploadMeasuresConstants.TemplateText.CsvValidationInvalidFileTypeText)</p>
					}
					if (Model?.MeasuresCsvErrors?.NotGbisSchema == true)
					{
						<p data-test-id="upload-measures-p-invalid-header-error-message" class="govuk-error-message">@(UploadMeasuresConstants.TemplateText.CsvValidationNotGBISSchemaText)</p>
					}
					if (Model?.MeasuresCsvErrors?.ExceedsMaxRows == true)
					{
						<p data-test-id="upload-measures-p-maxrows-error-message" class="govuk-error-message">@(UploadMeasuresConstants.TemplateText.CsvValidationExceedsMaxRowsText)</p>
					}
					if (Model?.MeasuresCsvErrors?.ExceedsMaxFileSize == true)
					{
						<p data-test-id="upload-measures-p-maxfilesize-error-message" class="govuk-error-message">@(UploadMeasuresConstants.TemplateText.CsvValidationExceedsMaxFileSizeText)</p>
					}
				}
			</div>
		}
			<input data-test-id="upload-measures-input-upload-measures-csv"
			class="custom-file-input"
			id="file-upload"
			type="file"
			name="MeasuresUploadFile"
			accept=".csv"
			tabindex="-1"
			aria-label="Upload a file"
			title="file-upload" />
		</form>

	</div>

	<button  data-test-id="upload-measures-btn-submit" class="govuk-button" form="measures-upload-form" data-module="govuk-button" type="submit"> Upload a measure file</button>

<hr class="govuk-section-break govuk-section-break--1 govuk-section-break--visible">

    <br>

    <h1 class="govuk-heading-l"> Get help </h1>

    <p class="govuk-body"> <a href="#">How to upload a measure (open a new tab)</a> </p>

    <p class="govuk-body"> <a href="#">What you will need to upload a Measure (opens in a new tab)</a> </p>

</div>